Add Weights & Biases logging
NVIDIAGameWorks/kaolin-wisp pull request #75
Opened 2022-12-01 14:26 UTC by soumik12345

This PR adds support for experiment tracking using [Weights & Biases](https://wandb.ai/site). In order to track training and validation metrics, render 3D interactive plots, reproduce the configurations and results, and many more features in a Weights & Biases workspace just add the additional flag `--wandb_project <your-project-name>` when initializing the training script.

Complete list of features supported by Weights & Biases:

- Log training and validation metrics in real-time.
- Log system metrics in real-time.
- Log RGB, RGBA, Depth renderings, etc. during training.
- Log interactive 360-degree renderings post-training in all levels of detail.
- Log model checkpoints as [Weights & Biases artifacts](https://wandb.ai/site/artifacts).
- Sync experiment configs for reproducibility.
- Host Tensorboard instance inside Weights & Biases run.

The full list of optional arguments related to logging on Weights & Biases includes:

- `--wandb_project`: Name of Weights & Biases project
- `--wandb_run_name`: Name of Weights & Biases run [Optional]
- `--wandb_entity`: Name of Weights & Biases entity under which your project resides [Optional]
- `--wandb_viz_nerf_angles`: Number of angles in the 360-degree renderings [Optional, default set to 20]
- `--wandb_viz_nerf_distance`: Camera distance to visualize Scene from for 360-degree renderings on Weights & Biases [Optional, default set to 3]

We also wrote a detailed report on [Variable Bitrate Neural Fields](https://wandb.ai/geekyrakshit/kaolin-wisp-integration/reports/Variable-Bitrate-Neural-Fields--VmlldzozMDE0MDY0) and its usage with kaolin-wisp. The report was published in our blog [Fully-Connected](https://wandb.ai/fully-connected).

[![](https://raw.githubusercontent.com/wandb/assets/main/wandb-github-badge-gradient.svg)](https://wandb.ai/geekyrakshit/kaolin-wisp-integration)

2022-12-04 12:41 UTC, orperel requested changes
Some changes are required to avoid breaking the interactive mode

2022-12-04 12:41 UTC, orperel commented on requirements.txt
> +wandb>=13.5
```suggestion
wandb>=0.13.5
```

2022-12-04 12:41 UTC, orperel commented on app/main_interactive.py
```suggestion
import wandb

```
(missing import)

2022-12-04 13:05 UTC, orperel commented
Hi @soumik12345 . 

Thank you so much for this beautiful PR! The VQAD report was also a delight to read.
I've tested your changes locally and some very minor modifications were required. We're excited to merge it, but before we do I should bring the following to your attention:

1. We're about to release a version with some breaking changes to our main scripts, to make them more friendly for future applications (we'll make sure to merge your changes first and support them moving forward). Once we do that, we may list VQAD as a separate app with its own README. We would be more than happy to to add a link within the VQAD readme to your report and W&B project, if you're interested.

2. We've been requested to ask external collaborators to sign a [Collaborator License Agreement](https://www.upcounsel.com/contributor-license-agreement). That should protect your rights as a contributor, but we would need to have it signed before we merge the PR. I'll have the details added soon

2022-12-04 13:19 UTC, soumik12345 commented
Hi @orperel Thanks a lot for your feedback on both the PR and the report.

1. It would be our immense pleasure to include a link to the updated VQAD application in our report. We would edit the report to include an updated and in-depth tutorial train the model after the changes.

2. As for the [Collaborator License Agreement](https://www.upcounsel.com/contributor-license-agreement), I would sign it ASAP to prevent any further delay.

2022-12-06 13:25 UTC, soumik12345 commented
> Hi @soumik12345 ! I've emailed you the CLA. I'm ready to merge as soon as you send it back. Thanks!

Hi @orperel I have signed the CLA and sent you on the same email thread.

2022-12-06 14:32 UTC, merged